apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p2bnu0m4k-dotnet-basic
  janus-idp.io/tekton: p2bnu0m4k-dotnet-basic
  backstage.io/kubernetes-id: p2bnu0m4k-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p2bnu0m4k-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
